@echo off
echo Установка зависимостей...
pip install -r requirements.txt
echo Запуск тестов...
pytest --alluredir=allure-results Conteragent_test.py
echo Генерация отчета...
allure serve allure-results
exit